package Shopping;



import com.mysql.jdbc.Statement;
import java.awt.Image;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sign_up.java
 *
 * Created on Mar 22, 2016, 9:14:32 PM
 */

/**
 *
 * @author Sunil
 */
public class sign_up extends javax.swing.JFrame{


    /** Creates new form sign_up */
    public sign_up() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");

        jDesktopPane1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setText("PHONE");
        jLabel8.setBounds(30, 390, 80, 22);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setText("GENDER");
        jLabel6.setBounds(30, 270, 59, 17);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel7.setText("Income");
        jLabel7.setBounds(30, 340, 53, 17);
        jDesktopPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setText("JOB");
        jLabel5.setBounds(30, 220, 28, 17);
        jDesktopPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("FIRST NAME");
        jLabel2.setBounds(30, 60, 100, 30);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("EMAIL/USERNAME");
        jLabel4.setBounds(30, 170, 170, 17);
        jDesktopPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel10.setText("PASSWORD");
        jLabel10.setBounds(30, 450, 82, 17);
        jDesktopPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("LAST NAME");
        jLabel3.setBounds(30, 120, 223, 17);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(180, 560, 127, 38);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.setBounds(250, 70, 180, 20);
        jDesktopPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.setBounds(250, 120, 182, 20);
        jDesktopPane1.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton2.setText("SIGN IN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(280, 610, 118, 20);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.setBounds(250, 170, 180, 20);
        jDesktopPane1.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "STUDENT", "BUSINESSMAN", "LAWYER", "HOUSEWIFE", "ENGINEER", "ANY OTHER PROFESSION" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.setBounds(250, 220, 182, 20);
        jDesktopPane1.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jRadioButton1.setBounds(250, 270, 60, 23);
        jDesktopPane1.add(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jRadioButton2.setBounds(250, 290, 80, 23);
        jDesktopPane1.add(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField5.setBounds(250, 390, 127, 20);
        jDesktopPane1.add(jTextField5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField4.setToolTipText("NOT MANDATORY");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.setBounds(250, 340, 127, 20);
        jDesktopPane1.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("ANY OTHER PROFESSION");
        jLabel9.setBounds(30, 320, 140, 14);
        jDesktopPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.setBounds(250, 320, 130, 20);
        jDesktopPane1.add(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel11.setBounds(0, 0, 0, 0);
        jDesktopPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("ANSWER THIS QUESTION IN CASE YOU FORGOT PASSWORD");
        jLabel13.setBounds(90, 480, 340, 14);
        jDesktopPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("ALREADY HAVE AN ACCOUNT?");
        jLabel12.setBounds(70, 610, 180, 14);
        jDesktopPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("WHAT'S YOUR FAVOURITE ANIMAL NAME?");
        jLabel14.setBounds(40, 510, 270, 14);
        jDesktopPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField8.setBounds(320, 510, 140, 20);
        jDesktopPane1.add(jTextField8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setBackground(new java.awt.Color(255, 255, 102));
        jLabel15.setBorder(javax.swing.BorderFactory.createTitledBorder("ADD PROFILE"));
        jLabel15.setBounds(470, 70, 190, 190);
        jDesktopPane1.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jPasswordField1.setBounds(250, 450, 130, 20);
        jDesktopPane1.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setForeground(new java.awt.Color(255, 102, 0));
        jButton3.setText("BROWSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(520, 280, 100, 23);
        jDesktopPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLabel16.setBounds(0, 0, 180, 80);
        jDesktopPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel17.setText("FILL THE FORM TO CREATE YOUR ACCOUNT");
        jLabel17.setBounds(10, 0, 720, 60);
        jDesktopPane1.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-743)/2, (screenSize.height-683)/2, 743, 683);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname=jTextField1.getText();
        String lname=jTextField2.getText();
        String email=jTextField3.getText();
        String income=jTextField4.getText();
        String phone=jTextField5.getText();
        Icon image=(Icon)jLabel15.getIcon();
        String password=new String(jPasswordField1.getPassword());
        String OPTJOB=jTextField7.getText();
        String Qs=jTextField8.getText();
        String job=" ";
         if(jComboBox1.getSelectedIndex()==0)
         {job= (String) jComboBox1.getSelectedItem();
         income="0";}
         else if(jComboBox1.getSelectedIndex()==1)
         job=(String) jComboBox1.getSelectedItem();
         else if  (jComboBox1.getSelectedIndex()==2)
            job=(String) jComboBox1.getSelectedItem();
         else if  (jComboBox1.getSelectedIndex()==3)
         {job=(String) jComboBox1.getSelectedItem();
          income="0";}
         else if  (jComboBox1.getSelectedIndex()==4)
            job=(String) jComboBox1.getSelectedItem();
        else if  (jComboBox1.getSelectedIndex()==5)
            job=(String) jComboBox1.getSelectedItem();
         else
         { job=(String) jComboBox1.getSelectedItem();}
         String gender=" ";
         {if(jRadioButton1.isSelected())
             gender="MALE";
         else if(jRadioButton2.isSelected())
             gender="female";}
         if(fname.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR FIRST NAME.");
         else  if(lname.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR LAST NAME.");
         else if(email.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR EMAIL.");
         else if(income.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR INCOME.");
         else  if(phone.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR PHONE NUMBER.");
         else if(password.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ENTER YOUR PASSWORD.");
         else if(job.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE SELECT YOUR JOB.");
         else if(gender.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE SELECT YOUR GENDER.");
         else if(Qs.isEmpty())
             JOptionPane.showMessageDialog(null,"PLEASE ANSWER THE QUESTION THAT FOLLOW.");
         else
         { try
          {  Class.forName("java.sql.DriverManager");
             Connection con=(Connection)
                     DriverManager.getConnection("jdbc:mysql://localhost:3306/shopping_app","root","bharat");
             Statement bk=(Statement) con.createStatement();
             String query="Insert into sign_up values('"+fname+"','"+lname+"','"+email+"','"+job+"','"+gender+"','"+income+"','"+phone+"','"+OPTJOB+"','"+password+"','"+Qs+"','"+image+"');";
             JOptionPane.showMessageDialog(null,"CLICK [OK] BUTTON TO CONFIRM.");
             bk.executeUpdate(query);
             JOptionPane.showMessageDialog(null,"ACCOUNT CREATED SUCCESSFULLY. \n  LOGIN TO SHOP");
             jTextField1.setText("");
             jTextField2.setText("");
             jTextField3.setText("");
             jTextField4.setText("");
             jTextField5.setText("");
             jPasswordField1.setText("");
             jTextField7.setText("");
             jRadioButton1.setSelected(false);
             jRadioButton2.setSelected(false);
             jTextField8.setText("");
             new SIGN_IN().setVisible(true);
             sign_up.this.dispose();
          }
          catch(Exception e)
          { JOptionPane.showMessageDialog(null,e.getMessage());}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                sign_up.this.dispose();
                new SIGN_IN().setVisible(true);
            

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         if(jComboBox1.getSelectedIndex()==0)
        { jLabel7.setVisible(false);
          jTextField4.setVisible(false);
         jTextField7.setVisible(false);
          jLabel9.setVisible(false);}
         else if(jComboBox1.getSelectedIndex()==1)
        { jLabel7.setVisible(true);
          jTextField4.setVisible(true);
       jTextField7.setVisible(false);
          jLabel9.setVisible(false);}
         else if(jComboBox1.getSelectedIndex()==2)
        { jLabel7.setVisible(true);
          jTextField4.setVisible(true);
       jTextField7.setVisible(false);
          jLabel9.setVisible(false);}
         else if(jComboBox1.getSelectedIndex()==3)
        { jLabel7.setVisible(false);
          jTextField4.setVisible(false);
         jTextField7.setVisible(false);
          jLabel9.setVisible(false);}
         else  if(jComboBox1.getSelectedIndex()==4)
        { jLabel7.setVisible(true);
          jTextField4.setVisible(true);
         jTextField7.setVisible(false);
          jLabel9.setVisible(false);}
         else if(jComboBox1.getSelectedIndex()==5)
        { jLabel7.setVisible(true);
          jTextField4.setVisible(true);
         jTextField7.setVisible(true);
          jLabel9.setVisible(true);
          JOptionPane.showMessageDialog(null,"PLEASE MENTION YOUR PROFESSION");}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String s;
         JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
            jLabel15.setIcon(ResizeImage(path));
             s = path;
             JOptionPane.showMessageDialog(null,"PROFILE PICTURE ADDED SUCCESSFULLY.");
         }
         else if(result == JFileChooser.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null,"PLEASE SELECT IMAGE");
         }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
     ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(jLabel15.getWidth(), jLabel15.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;}
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
